framework:
    secret: '%env(APP_SECRET)%'

    session:
        handler_id: null
        cookie_lifetime: 3600 # Durée de vie du cookie
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        storage_factory_id: 'session.storage.factory.native' # Utilisation de la session native en prod

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file # Utilisation de la session mockée pour les tests
