security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginAuthenticator
            logout:
                path: app_logout
                target: home # Redirection après déconnexion (ajouté pour éviter les erreurs)

            # Spécifier l'entry_point pour gérer la redirection des utilisateurs anonymes
            entry_point: App\Security\LoginAuthenticator

            # Configuration du formulaire de connexion (inutile si vous utilisez un authentificateur personnalisé)
            form_login:
                login_path: login
                check_path: login
                default_target_path: home

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # Durée de vie du cookie "se souvenir de moi" (7 jours)
                path: /

    access_control:
        # Routes accessibles uniquement aux administrateurs
        - { path: ^/admin, roles: ROLE_ADMIN }

        # Routes accessibles uniquement aux utilisateurs connectés
        - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/mes-tickets, roles: ROLE_USER }
        - { path: ^/paiement, roles: ROLE_USER }
        - { path: ^/contact, roles: ROLE_USER }
        - { path: ^/home, roles: ROLE_USER }
        - { path: ^/ticket/mes-tickets, roles: ROLE_USER }

        # Routes publiques accessibles à tous
        - { path: ^/login, roles: PUBLIC_ACCESS }
        - { path: ^/reset-password, roles: PUBLIC_ACCESS }
        - { path: ^/reset, roles: PUBLIC_ACCESS }

        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/$, roles: PUBLIC_ACCESS }
        - { path: ^/placeholder.svg, roles: PUBLIC_ACCESS }

        # Blocage général de tout le reste
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
