controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home:
    path: /home
    controller: App\Controller\HomeController::index

ai:
    path: /ai
    controller: App\Controller\AIController::prompt

openrouter:
    path: /openrouter
    controller: App\Controller\OpenRouterController::prompt
